# Receiver = Pioneer VSX-520
# Remote = AXD7587

# Basic code for setting transmitter and sending commands to Pioneer unit
# remote_transmitter:
#   pin: GPIO12
#   carrier_duty_percent: 50%

# button:
#   - platform: template
#     name: "Mute"
#     on_press:
#       - remote_transmitter.transmit_pioneer:
#           rc_code_1: 0xA512
#           # rc_code_2: 0xA512
#           repeat:
#             times: 2

substitutions:
  # Codes
  # Top Section
  # VSX-520_power: 
  VSX-520_sleep: [0xA548]
  # VSX-520_source: 
  # VSX-520_receiver: 
  VSX-520_prev_input: [0xA556, 0xA5C1]
  VSX-520_next_input: [0xA555]
  VSX-520_bd: [0xA55C, 0xA5C0]
  VSX-520_dvd: [0xA585]
  VSX-520_tv: [0xA50C]
  VSX-520_dvr: [0xA589]
  VSX-520_cd: [0xA54C]
  VSX-520_cd-r: [0xA588]
  VSX-520_adapter: [0xA55C, 0xA5C4]
  VSX-520_tuner: [0xA547]
  VSX-520_eq: [0xA59F, 0xA5DC]
  VSX-520_phase: [0xA55A, 0xA5CB]
  VSX-520_s_retriever: [0xA55A, 0xA5CD]
  VSX-520_signal_sel: [0xA556, 0xA503]
  
  # TV Control Section
  VSX-520_tv_power: 0x551C
  VSX-520_tv_input: 0x5513
  VSX-520_tv_ch_up: 0x5510
  VSX-520_tv_ch_dwn: 0x5511
  VSX-520_tv_vol_up: 0x550A
  VSX-520_tv_vol_dwn: 0x550B
  
  
  
