substitutions:
  upd_frq: 60s
  ir_dump: "pioneer"
  remote: "VSX-520"
  ${remote}_mute: 0xA512
  ir_target: "VSX-520"

remote_transmitter:
  pin: GPIO12
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Mute"
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0xA512
          repeat:
            times: 2

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: True
    name: Physical Button
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: ${${ir_target}_mute}
          rc_code_2: ${${ir_target}_mute}

remote_receiver:
  id: IR_Receiver
  pin: 
    number: GPIO13
    inverted: true
  dump: ${ir_dump}
  # Settings to optimize recognition of RF devices
  tolerance: 25%

sensor:
  - platform: dht
    model: "DHT11"
    pin: GPIO21
    id: sensor_dht11
    temperature:
      id: "temperature"
      name: "DHT11 Temperature"
    humidity:
      id: "humidity"
      name: "DHT11 Humidity"
      # on_value_range:
      #   - above: 65.0
      #     then:
      #       - switch.turn_on: dehumidifier1
      #   - below: 50.0
      #     then:
      #       - switch.turn_off: dehumidifier1
    update_interval: ${upd_frq}
    


