substitutions:
  upd_frq: 60s

remote_transmitter:
  pin: GPIO12
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "Enable IR Receiver"
    restore_mode: ALWAYS_ON
    optimistic: True
    turn_on_action:
      then:
        - component.enable: IR_Receiver
    turn_off_action:
      then:
        - component.disable: IR_Receiver

button:
  - platform: template
    name: "Mute x1"
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0xA512
          # rc_code_2: 0xA512

  - platform: template
    name: "Mute x2"
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0xA512
          repeat:
            times: 2

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: 0xA512
          repeat:
            times: 2

remote_receiver:
  id: IR_Receiver
  pin: 
    number: GPIO13
    inverted: true
  dump: all
  # Settings to optimize recognition of RF devices
  tolerance: 25%

# sensor:
#   - platform: dht
#     model: "DHT11"
#     pin: GPIO21
#     id: sensor_dht11
#     temperature:
#       id: "temperature"
#       name: "DHT11 Temperature"
#     humidity:
#       id: "humidity"
#       name: "DHT11 Humidity"
#       # on_value_range:
#       #   - above: 65.0
#       #     then:
#       #       - switch.turn_on: dehumidifier1
#       #   - below: 50.0
#       #     then:
#       #       - switch.turn_off: dehumidifier1
#     update_interval: ${upd_frq}
    
#   - platform: dht
#     model: "DHT11"
#     pin: GPIO14
#     id: sensor_dht11_2
#     temperature:
#       id: "temperature_2"
#       name: "DHT11 Temperature 2"
#     humidity:
#       id: "humidity_2"
#       name: "DHT11 Humidity 2"
#       # on_value_range:
#       #   - above: 65.0
#       #     then:
#       #       - switch.turn_on: dehumidifier1
#       #   - below: 50.0
#       #     then:
#       #       - switch.turn_off: dehumidifier1
#     update_interval: ${upd_frq}

