sensor:
  - platform: dht
    model: "DHT11"
    pin: GPIO21
    temperature:
      id: "temperature"
      name: "DHT11 Temperature"
    humidity:
      id: "humidity"
      name: "DHT11 Humidity"
      # on_value_range:
      #   - above: 65.0
      #     then:
      #       - switch.turn_on: dehumidifier1
      #   - below: 50.0
      #     then:
      #       - switch.turn_off: dehumidifier1
    update_interval: 30s

light:
  - platform: monochromatic
    name: "Red LED"
    output: output_component1
    id: red_led

  - platform: monochromatic
    name: "Yellow LED"
    output: output_component2
    id: yellow_led

output:
  - platform: ledc
    id: output_component1
    pin: GPIO48

  - platform: ledc
    id: output_component2
    pin: GPIO14

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - light.toggle: red_led
      - delay: 0.5s
      - light.toggle: yellow_led
