substitutions:
  upd_frq: 60s

remote_transmitter:
  pin: GPIO12
  carrier_duty_percent: 50%

# button:
#   - platform: template
#     name: "IR Transmitter Button"
#     on_press:
#       - remote_transmitter.transmit_raw:
#           code: [0000, 006D, 0021, 0000, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 003C, 0015, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 003C, 0016, 003C, 0016, 0099]
#       - logger.log: "IR Button Pressed"
  

remote_receiver:
  pin: GPIO13
  dump: all
  # id: ir_receiver
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 250us
  idle: 4ms

sensor:
  - platform: dht
    model: "DHT11"
    pin: GPIO21
    id: sensor_dht11
    temperature:
      id: "temperature"
      name: "DHT11 Temperature"
    humidity:
      id: "humidity"
      name: "DHT11 Humidity"
      # on_value_range:
      #   - above: 65.0
      #     then:
      #       - switch.turn_on: dehumidifier1
      #   - below: 50.0
      #     then:
      #       - switch.turn_off: dehumidifier1
    update_interval: ${upd_frq}
    
  - platform: dht
    model: "DHT11"
    pin: GPIO14
    id: sensor_dht11_2
    temperature:
      id: "temperature_2"
      name: "DHT11 Temperature 2"
    humidity:
      id: "humidity_2"
      name: "DHT11 Humidity 2"
      # on_value_range:
      #   - above: 65.0
      #     then:
      #       - switch.turn_on: dehumidifier1
      #   - below: 50.0
      #     then:
      #       - switch.turn_off: dehumidifier1
    update_interval: ${upd_frq}

# light:
#   - platform: monochromatic
#     name: "Red LED"
#     output: output_component1
#     id: red_led

#   - platform: monochromatic
#     name: "Yellow LED"
#     output: output_component2
#     id: yellow_led

# output:
#   - platform: ledc
#     id: output_component1
#     pin: GPIO13

#   - platform: ledc
#     id: output_component2
#     pin: GPIO14

# button:
#   - platform: template
#     name: "Template Button"
#     on_press:
#       - logger.log: Button Pressed

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - remote_transmitter.transmit_raw:
          code: [0000, 006D, 0021, 0000, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 003C, 0015, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 0013, 0016, 0013, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 003C, 0016, 0013, 0016, 003C, 0016, 003C, 0016, 003C, 0016, 0099]
      - logger.log: IR Button Pressed
      # - component.update: sensor_dht11
      # - light.toggle: red_led
      # - delay: 0.5s
      # - light.toggle: yellow_led
