# https://esphome.io/automations/actions/
# ---------------------------------
sensor:
  - platform: mpu6050
    address: 0x68
    accel_x:
      name: "MPU6050 Accel X"
    accel_y:
      name: "MPU6050 Accel Y"
    accel_z:
      name: "MPU6050 Accel z"
    gyro_x:
      name: "MPU6050 Gyro X"
    gyro_y:
      name: "MPU6050 Gyro Y"
    gyro_z:
      name: "MPU6050 Gyro z"
    temperature:
      name: "MPU6050 Temperature"
    update_interval: 20s

i2c:
  - id: bus_a
    sda: GPIO10
    scl: GPIO11
    scan: true
    
# ---------------------------------
sensor:
  - platform: dallas_temp
    name: "DS18B20 Temperature"
    update_interval: 5s
    one_wire_id: OWTemp

one_wire:
  - platform: gpio
    pin: GPIO13
    id: OWTemp
# ---------------------------------


# ---------------------------------
on_...:
  then:
    - if:
        condition:
          lambda: 'return id(some_sensor).state < 30;'
        then:
          - logger.log: "The sensor value is below 30!"
          - light.turn_on: my_light
          - delay: 5s
        else:
          - logger.log: "The sensor value is above 30!"
    - light.turn_off: my_light

on_...:
  - while:
      condition:
        binary_sensor.is_on: some_binary_sensor
      then:
      - logger.log: "Still executing"
      - light.toggle: some_light
      - delay: 5s

on_...:
  - logger.log: "Waiting for binary sensor"
  - wait_until:
      condition:
        binary_sensor.is_on: some_binary_sensor
      timeout: 8s
  - logger.log: "Binary sensor might be ready"

on_...:
  then:
    - component.suspend: my_component
    - component.resume: my_component
    - component.update: my_component

on_...:
  then:
    - if:
        condition:
          # Same syntax for `and` as well as `xor` conditions
          or:
            - binary_sensor.is_on: some_binary_sensor
            - binary_sensor.is_on: other_binary_sensor
        # ...
    - if:
        any:
          - not:
              binary_sensor.is_off: some_binary_sensor
          - binary_sensor.is_on: some_other_sensor

on_...:
  if:
    condition:
      for:
        time: 5min
        condition:
          api.connected:
    then:
      - logger.log: API has stayed connected for at least 5 minutes!
# ---------------------------------




light:
  - platform: monochromatic
    name: "Red LED"
    output: output_component1
    id: red_led

  - platform: monochromatic
    name: "Yellow LED"
    output: output_component2
    id: yellow_led

output:
  - platform: ledc
    id: output_component1
    pin: GPIO13

  - platform: ledc
    id: output_component2
    pin: GPIO14

button:
  - platform: template
    name: "Template Button"
    on_press:
      - logger.log: Button Pressed

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - remote_transmitter.transmit_raw:
          code: ""
      - logger.log: IR Button Pressed
      - component.update: sensor_dht11
      - light.toggle: red_led
      - delay: 0.5s
      - light.toggle: yellow_led
